# Generated by Django 2.0.10 on 2019-02-12 13:31

from django.db import migrations

import wagtail_simple_gallery.fields


class Migration(migrations.Migration):
	dependencies = [
		('wagtail_simple_gallery', '0004_auto_20190131_1220'),
	]

	operations = [
		migrations.AddField(
			model_name='simplegallerypage',
			name='highlight',
			field=wagtail_simple_gallery.fields.UniqueBooleanField(default=False,
																   help_text='If page will be highlight.',
																   verbose_name='Highlight'),
		),
	]